# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-28 23:39
from __future__ import unicode_literals

from django.db import migrations
import django_bleach.models


class Migration(migrations.Migration):

    dependencies = [
        ('osm_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=django_bleach.models.BleachField(max_length=256),
        ),
    ]
