# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-30 00:03
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osm_web', '0002_auto_20171128_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='description', unique=True),
        ),
    ]
