# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-12-20 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osm_web', '0006_auto_20171220_1029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ask',
            name='asker',
        ),
        migrations.RemoveField(
            model_name='ask',
            name='project',
        ),
        migrations.AddField(
            model_name='ask',
            name='stake',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='osm_web.Stake'),
            preserve_default=False,
        ),
    ]
