# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-31 22:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('osm_web', '0010_auto_20180117_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ask',
            name='price',
            field=models.PositiveIntegerField(help_text='reputation points per share', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)]),
        ),
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osm_web.UserProfile'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='price',
            field=models.PositiveIntegerField(help_text='reputation points per share', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000000000)]),
        ),
    ]
