# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-21 17:16
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('osm_web', '0011_auto_20180131_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('user__first_name', 'user__last_name'), unique=True),
        ),
    ]
